{
 "title": "RTC Engine metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "room",
    "label": "Room",
    "query": "select distinct room_id from peers_metrics;"
   },
   {
    "name": "peer",
    "label": "Peer",
    "query": "select distinct peer_id from peers_metrics where room_id = '${room:csv}';"
   }
  ]
 },
 "panels": [
  {
   "title": "Tracks metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tracks data",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\ndistinct\n  track_id as \"track ID\",\n  \"inbound-rtp.ssrc\" as SSRC,\n  \"inbound-rtp.encoding\" as encoding \nFROM tracks_metrics\nWHERE\n  -- $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  track_id AS metric,\n  \"inbound-rtp.bytes_received\"\nFROM tracks_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "frames received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  track_id AS metric,\n  \"inbound-rtp.frames\"\nFROM tracks_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  track_id AS metric,\n  \"inbound-rtp.packets\"\nFROM tracks_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "keyframe requests sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  track_id AS metric,\n  \"inbound-rtp.keyframe_request_sent\"\nFROM tracks_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "keyframes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  track_id AS metric,\n  \"inbound-rtp.keyframes\"\nFROM tracks_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "ICE metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "bytes sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  peer_id AS metric,\n  \"ice.bytes_sent\"\nFROM peers_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "bytes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  peer_id AS metric,\n  \"ice.bytes_received\"\nFROM peers_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  peer_id AS metric,\n  \"ice.packets_sent\"\nFROM peers_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "packets received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  peer_id AS metric,\n  \"ice.packets_received\"\nFROM peers_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Binding Responses sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  peer_id AS metric,\n  \"ice.binding_responses_sent\"\nFROM peers_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Binding Requests received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT\n  inserted_at AS \"time\",\n  peer_id AS metric,\n  \"ice.binding_requests_received\"\nFROM peers_metrics\nWHERE\n  $__timeFilter(inserted_at) AND\n  peer_id = '$peer'\nORDER BY 1,2"
      }
     ]
    }
   ]
  }
 ]
}